<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Configuration>Release</Configuration>
        <AssemblyName>BringBackContainers</AssemblyName>
        <Version>1.1.0</Version>
    </PropertyGroup>

    <Target Name="RemoveDirectories" BeforeTargets="BeforeBuild">
        <RemoveDir Directories="./bin/;./build/;./dist/" />
    </Target>

    <Target Name="CopyCustomContent" AfterTargets="AfterBuild">
        <ItemGroup>
            <DataFiles Include="bin\$(Configuration)\$(TargetFramework)\data\**\*" />
        </ItemGroup>
        <Copy SourceFiles="bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).dll"
              DestinationFolder="./build/SPT_Runtime/user/mods/$(AssemblyName)/" />
        <Copy SourceFiles="@(DataFiles)"
              DestinationFolder="./build/SPT_Runtime/user/mods/$(AssemblyName)/data/%(RecursiveDir)"
              SkipUnchangedFiles="true" Condition="'@(DataFiles)' != ''" />
    </Target>

    <Target Name="ZipOutputPath" AfterTargets="Build">
        <MakeDir Directories="./dist" Condition="!Exists('./dist')" />
        <Delete Files="./dist/$(AssemblyName)-$(Version).zip"
                Condition="Exists('./dist/$(AssemblyName)-$(Version).zip')" />
        <ZipDirectory SourceDirectory="./build"
                      DestinationFile="./dist/$(AssemblyName)-$(Version).zip" />
    </Target>

    <ItemGroup>
        <PackageReference Include="SPTushonka.Common" Version="4.1.3" />
        <PackageReference Include="SPTushonka.DI" Version="4.1.3" />
        <PackageReference Include="SPTushonka.Server.Core" Version="4.1.3" />
    </ItemGroup>

    <ItemGroup>
      <None Update="data\config.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
